config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
   root to:'readings#new'

  # Example resource route (maps HTTP verbs to controller actions automatically):
     resource :reading

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/reading.rb
class Reading
  include ActiveModel::Model
  attr_accessor :start_date, :end_date
  validates :start_date, :end_date, presence: true
  validates :parsed_start_date, :parsed_end_date, date: { 
    after: Date.parse('2006-09-20'),
    before: Date.today
  }
  validates :parsed_start_date, date: {
    before: Proc.new {|obj| obj.parsed_end_date }
  }
  validates :parsed_end_date, date: { 
    after: Proc.new {|obj| obj.parsed_start_date } 
  }
  validates :parsed_end_date, date: { before: Proc.new {|obj| obj.parsed_start_date + 7.days } }
  # using virtual attributes because not automatically type cast
  # to a Date object
  def parsed_start_date
    Date.parse(start_date)
  end
  def parsed_end_date
    Date.parse(end_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/readings_controller.rb
require 'pp'

class ReadingsController < ApplicationController
  def new
    @reading = Reading.new
  end

  def create
    @reading = Reading.new(reading_params)

    if @reading.valid?
      # serialize the object into a cookie
      #
      # redirect_to :show
    else
      # errors here: @reading.errors.messages
      # also look at @reading.errors.full_messages

      # flash.now[:error] = "There was a problem with your submission"

      # re-render new action and display flash error (maybe highlight the invalid fields)
    end
  end

  def show
    # pull the reading model out of the cookie
    #
    # display the final result -- you'll need to add stats methods
    # to the Reading model and use the reading model to fetch data
    # via the WeatherClient
  end

  private

  def reading_params
    params.require(:reading).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<%= yield %>
</body>
</html>

app/views/readings/new.html.erb
<h1>*** Lake Pend Orielle Readings at Deep Moor Station ***</h1>
<p>
Computes the mean and median of the wind speed, air temperature,
and barometric pressure recorded at the Deep Moor station on Lake
Pend Orielle for a given range of dates.
</p>
<br/>
<div id='reading-form'>
  <%# need to specify url because it's a singular resource and %>
  <%# actionview doesn't deal with those automatically %>
  <%= form_for @reading, url: reading_path do |f| %>
  <div class='field'>
    <%= f.label 'Start Date' %>
    <%= f.text_field :start_date, placeholder: 'YYYY-MM-DD' %>
  </div>
  <div class='field'>
    <%= f.label 'End Date' %>
    <%= f.text_field :end_date, placeholder: 'YYYY-MM-DD' %>
  </div>
    <%= f.submit 'Submit' %>
  <% end %>
</div>